"""Build the Ukrainian supplement from original SR28 flat files, without an API.

Usage: python3 scripts/import_usda.py /path/to/usda-sqlite/data
Only translations are edited manually. Nutrient values are copied from NUT_DATA.
"""
import csv
import hashlib
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_REVISION = '1e457b599af101ce463a195867574eba16c81acb'
SOURCE_MIRROR = f'https://github.com/alyssaq/usda-sqlite/tree/{SOURCE_REVISION}/data'
FIELDS = {'208': 'kcal', '203': 'p', '204': 'f', '205': 'c', '291': 'fiber'}
CATEGORIES = {'0100': 'Молочні продукти та яйця', '0900': 'Фрукти та ягоди',
              '1100': 'Овочі та гриби', '1200': 'Горіхи та насіння',
              '1500': 'Риба та морепродукти', '1600': 'Бобові', '2000': 'Крупи та борошно'}

def rows(file):
    with file.open(encoding='latin-1', newline='') as stream:
        yield from csv.reader(stream, delimiter='^', quotechar='~')

def build(source):
    translations = {}
    for line in (ROOT / 'data/usda-food-names-uk.txt').read_text().splitlines():
        if not line.strip() or line.startswith('#'):
            continue
        ndb, name, aliases = line.split('|')
        assert ndb not in translations, ndb
        translations[ndb] = (name, [x for x in aliases.split(';') if x])
    descriptions = {r[0]: r for r in rows(source / 'FOOD_DES.txt') if r[0] in translations}
    nutrients = {ndb: {} for ndb in translations}
    evidence = []
    for row in rows(source / 'NUT_DATA.txt'):
        ndb, nutrient, amount = row[:3]
        if ndb in translations and nutrient in FIELDS:
            value = float(amount)
            assert math.isfinite(value) and value >= 0
            if nutrient != '208':
                assert value <= 100, (ndb, nutrient)
            nutrients[ndb][FIELDS[nutrient]] = value
            evidence.append({'ndb': ndb, 'nutrient': nutrient, 'amount': amount})
    foods = []
    for ndb, (name, aliases) in translations.items():
        row = descriptions[ndb]
        if set(nutrients[ndb]) != set(FIELDS.values()):
            print(f'Skipped {ndb} ({name}): incomplete nutrient data')
            continue
        foods.append({'id': f'usda-sr28-{ndb}', 'canonicalId': f'usda-sr28-{ndb}',
            'name': name, 'nameOriginal': row[2], 'category': CATEGORIES[row[1]],
            **nutrients[ndb], 'aliases': [row[2], *aliases], 'source': 'built-in', 'core': True,
            'nutrientSource': 'USDA SR28 (2015)', 'sourceRecordId': ndb,
            'sourceUrl': 'https://fdc.nal.usda.gov/data-documentation/', 'per': '100g'})
    evidence_file = {'dataset': 'USDA National Nutrient Database, SR28',
        'mirror': SOURCE_MIRROR, 'revision': SOURCE_REVISION,
        'sha256': {name: hashlib.sha256((source / name).read_bytes()).hexdigest()
                   for name in ['FOOD_DES.txt', 'NUT_DATA.txt']},
        'descriptions': {ndb: row[2] for ndb, row in descriptions.items()},
        'nutrients': evidence}
    (ROOT / 'data/usda-sr28-source-extract.json').write_text(json.dumps(evidence_file, ensure_ascii=False, indent=2) + '\n')
    js = '''/* Generated by scripts/import_usda.py from USDA SR28. Values per 100 g. */
(function(root) {
    'use strict';
    const extra = FOOD_DATA;
    const canonical = root.ACHILLES_FOOD_CORE_CANONICAL;
    const index = root.ACHILLES_FOOD_SEARCH_INDEX;
    const seen = new Set(canonical.map(item => item.id));
    for (const food of extra) {
        if (seen.has(food.id)) continue;
        seen.add(food.id);
        canonical.push(food);
        for (const q of [food.name, ...food.aliases])
            index.push({q, id: food.id, boost: 260, kind: 'sourced'});
    }
    Object.assign(root.ACHILLES_FOOD_CORE_META, {
        version: '10.15.1', name: 'Achilles Food Core',
        canonicalProfiles: canonical.length, searchRecords: index.length,
        sourcedProfiles: extra.length
    });
})(window);
'''.replace('FOOD_DATA', json.dumps(foods, ensure_ascii=False, separators=(',', ':')))
    (ROOT / 'foods_ua_extra.js').write_text(js)
    print(f'Imported {len(foods)} distinct USDA profiles')

if __name__ == '__main__':
    build(Path(sys.argv[1]))
